### ISSUE TITLE
Ability to use different Homepage images for each country roll out

### ISSUE THREAD

**Issue by Botswang** [universalcore/unicore#104]
### Is there clear value to clients/users (the grandma test)?

Yes, in the case of FFL each Unicef country office wants the website to be unique
### Have real-world users been consulted in designing the feature?

Yes
### Can it be measured?

No
### Can be shipped in 2-4 weeks?

Yes
### Has a mockup been created?

No
### Did we pivot?

No
### Is it coupled to a project?

FFL but it can be a feature used across the board
### Is it bloggable/slackable/tweetable?

Yes
### Compound value, will it be used elsewhere?

Has not been requested outside of FFL for the moment. 
### Has a partner or client be consulted, interviewed?

Client (Unicef) requested it

**Comment by miltontony** [comment]
@smn we need a model in order for this to end up in json. Where is the logical place to put this? `ContentRepository` or should I create a site preferences thing?

**Comment by smn** [comment]
either a `Site` thing or attach to the `Localisation` object?
