### ISSUE TITLE
Swahili categories have the same background

### ISSUE THREAD

**Issue by tsepot** [universalcore/unicore#108]
Please note that the swahili categories have the same background and #content span.category-“category" anchor color is not specified under the category-recommended

![screen shot 2014-11-10 at 5 14 57 pm](https://cloud.githubusercontent.com/assets/8982805/4978017/61c49856-68ec-11e4-99c9-f93bc01b83d9.png)

**Comment by miltontony** [comment]
For MAMA colors to work, all category slugs must be in english
e.g `slug='mama-to-mama'`, `slug='baby'` and `slug='pregnancy'`
This needs to be changed via the CMS

**Comment by tsepot** [comment]
When slug is changed the colors work.
