### ISSUE TITLE
Option to hide date in Article Listing

### ISSUE THREAD

**Issue by pippayeats** [universalcore/unicore#117]
The option to hide the date in the article listing view (e.g. on homepage or category listing).
Is there clear value to clients/users (the grandma test)?
Yes, for clients who are not creating content regularly this helps with being able to re-feature content on the homepage without it seeming dated. 

Have real-world users been consulted in designing the feature?
Request from client to remove dates, discussion with B & Pippa about use cases and reasons dates should be kept but made less prominent in UI.

Can it be measured?
We could do a test for views on new vs older content that is randomly presented to users and see if 'dated' content is less viewed. However not sure this is necessary.

Can be shipped in 2-4 weeks?
Yes.

Has a mockup been created?
No. 

Did we pivot?

Is it coupled to a project?
Yes, FFL.

Is it bloggable/slackable/tweetable?
No.

Compound value, will it be used elsewhere?
Yes. 

Has a partner or client be consulted, interviewed?
Yes, MAMA.

**Comment by miltontony** [comment]
Simon is unhappy about not dating it at all. Preferences is to make the date less prominent (moving it at the bottom, or lighter color, etc)

**Comment by SteveBarnett** [comment]
I agree that not having a date at all isn't ideal. When the date isn't immediately relevant to the content, moving it to the bottom of the page is a common pattern.

**Comment by smn** [comment]
Haven't had any further request on changing this. Closing but feel free to re-open if needed.

**Comment by Tamsendb** [comment]
@smn did you move the date to the bottom of the page? I know we relayed to MAMA team that this is what we were going to do - they were in agreement with this, so just checking ...
