### ISSUE TITLE
Posts should be searchable.

### ISSUE THREAD

**Issue by smn** [universalcore/unicore#12]
<a href="https://github.com/smn"><img src="https://avatars.githubusercontent.com/u/1065?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [smn](https://github.com/smn)**
_Friday Sep 12, 2014 at 14:53 GMT_
_Originally opened as https://github.com/universalcore/universalcore.github.io/issues/12_

---
### Is there clear value to clients/users (the grandma test)?

Posts are currently only browsable through pagination.
Adding full text search creates a much better experience for people searching specific content.
### Have real-world users been consulted in designing the feature?

Tamsen
### Can it be measured?

Page views should go up as on YAL & MAMA search is a heavily used feature.
### Can be shipped in 2-4 weeks?

Yes
### Has a mockup been created?

No
### Did we pivot?

No, already exists on YAL & MAMA.
### Is it coupled to a project?

FFL, MAMA & GEM

**Comment by miltontony** [comment]
@smn to speak to Jonathan about briefs for studio
