### ISSUE TITLE
Batch uploading from Word documents: a solution is sought in advance of the incoming 100 x articles from Baby Center

### ISSUE THREAD

**Issue by Tamsendb** [universalcore/unicore#135]

**Comment by SteveBarnett** [comment]
@Tamsendb Can you get us a sample of one of the Word docs? Doesn't have to be finished.

Also: I thought that they were using the CMS now? :confused:

**Comment by smn** [comment]
Yeah. Using the CMS, not import MS Word, don't really understand where this is coming from?

**Comment by smn** [comment]
Closing because in the last call I was in with BC they'd decided to use the CMS. Please re-open if mistaken.
