### ISSUE TITLE
MNM | Article links return error "Unknown file format" | Nokia C1 

### ISSUE THREAD

**Issue by tsepot** [universalcore/unicore#136]
All article link return an error "Unknown file format" on http://za.mnm.qa-hub.unicore.io/ for the Nokia C1 device. All images on the site for this device are broken.
![img_0497](https://cloud.githubusercontent.com/assets/8982805/5644273/6c306512-966a-11e4-8ac2-b9600ebd8a9c.JPG)

**Comment by smn** [comment]
@tsepot please visit http://requestb.in/1ipnarv1 and ping me when done so I can see what http headers the phone sends.

**Comment by smn** [comment]
Does this also happen on other unicore sites? Can you check?

**Comment by tsepot** [comment]
@smn I tried mama, gem, ebola and ffl qa site I am getting that error when accessing the links, the device does not even load the home page for those.
