### ISSUE TITLE
Content authors need to be able to publish content to a UC site.

### ISSUE THREAD

**Issue by smn** [universalcore/unicore#16]
<a href="https://github.com/smn"><img src="https://avatars.githubusercontent.com/u/1065?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [smn](https://github.com/smn)**
_Friday Sep 12, 2014 at 15:10 GMT_
_Originally opened as https://github.com/universalcore/universalcore.github.io/issues/16_

---
### Is there clear value to clients/users (the grandma test)?

Content management is separate from the actual site where it is displayed. The final step of publishing involves notifying a site that content has changed and that it can be pulled in. Content authors need to be able to do this without developer support.
### Have real-world users been consulted in designing the feature?

No.
### Can it be measured?

Yes, content deploys should happen in less than a minute.
### Can be shipped in 2-4 weeks?

Yes
### Has a mockup been created?

No
### Did we pivot?

No, we've not done this before.
### Is it coupled to a project?

GEM, FFL & MAMA.
### Is it bloggable/slackable/tweetable?

Yes
### Compound value, will it be used elsewhere?

Potentially yes as it adds a new concept of decentralisation to how content is managed.

**Comment by smn** [comment]
@miltontony is this already happening but implicitly in the background with Celery & GitHub webhooks?

**Comment by miltontony** [comment]
@smn yes, this is the background magic

**Comment by smn** [comment]
@miltontony I'm moving this to done because it essentially is for now (even though there is still more to be done in the future).

**Comment by smn** [comment]
The code doing this is currently here: https://github.com/praekelt/unicore-cms-django/blob/develop/cms/models.py#L189-L190
