### ISSUE TITLE
Content authors need to be able to link articles together.

### ISSUE THREAD

**Issue by smn** [universalcore/unicore#36]
### Have real-world users been consulted in designing the feature?

BC & Tamsen
### Can be shipped in 2-4 weeks?

Yes
### Has a mockup been created?

No
### Did we pivot?

No
### Is it coupled to a project?

MAMA
### Compound value, will it be used elsewhere?

UC core feature.
### Has a partner or client be consulted, interviewed?

BC

**Comment by tsepot** [comment]
@smn option to link articles on the CMS is there however the article are not showing on the front end, to test the functionality, should I link articles of the same category, articles of the same language?

**Comment by smn** [comment]
You're right, those aren't displaying yet on the front-end, will fix.

**Comment by smn** [comment]
The page where related pages have been provided now show them: http://tz.qa.mama.unicore.io/content/detail/62b3da9f89ba412ba37bda861084a22a/

**Comment by tsepot** [comment]
Linking articles works for MAMA
