### ISSUE TITLE
Content authors need to be able to specify deployment targets.

### ISSUE THREAD

**Issue by smn** [universalcore/unicore#38]
### Is there clear value to clients/users (the grandma test)?

Not all content should be published everywhere. Targets allow the UC cms to determine which content should be committed to which content repo.
### Have real-world users been consulted in designing the feature?

No
### Can it be measured?

Yes
### Can be shipped in 2-4 weeks?

Yes
### Has a mockup been created?

No
### Did we pivot?

We've tried this before but failed because it grew too complex.
### Is it coupled to a project?

MAMA w/ BC content.
### Is it bloggable/slackable/tweetable?

Yes
### Compound value, will it be used elsewhere?

Mozilla
### Has a partner or client be consulted, interviewed?

BC

**Comment by miltontony** [comment]
@smn what's holding this up in QA?

**Comment by smn** [comment]
Nothing. It's already in production so we should just close it.

**Comment by smn** [comment]
It's just not as feature complete as we'd like to see it but we'll get there eventually. For those future things we should create new tickets. Closing this.
