### ISSUE TITLE
Content authors need to be able to upload images.

### ISSUE THREAD

**Issue by smn** [universalcore/unicore#5]
<a href="https://github.com/smn"><img src="https://avatars.githubusercontent.com/u/1065?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [smn](https://github.com/smn)**
_Friday Sep 12, 2014 at 14:15 GMT_
_Originally opened as https://github.com/universalcore/universalcore.github.io/issues/5_

---
### Is there clear value to clients/users (the grandma test)?

Images need to be able to to:
1. uploaded
2. removed
### Have real-world users been consulted in designing the feature?

Praekelt head of content
### Can it be measured?

Binary
### Can be shipped in 2-4 weeks?

Yes
### Has a mockup been created?

No.
### Did we pivot?

We know this feature well from MAMA & YAL
### Is it coupled to a project?

FFL & MAMA
### Is it bloggable/slackable/tweetable?

Potentially though not very exciting.
### Compound value, will it be used elsewhere?

This potentially leads to a photologue replacement for how we deal with uploaded images and the ability to have these created at different dimensions for better mobile consumption.
### Has a partner or client be consulted, interviewed?

FFL & MAMA

**Comment by miltontony** [comment]
consider serving media directly from views
e.g
`/media/<image uuid>.png` which then serves content directly from `.repo/images/<image uuid>.png`

**Comment by smn** [comment]
http://thumbor.org may be a good thing to look at.

**Comment by SteveBarnett** [comment]
All images should have `alt` text. Or at the very least a blank `alt` attribute.

**Comment by miltontony** [comment]
@tsepot This has been added for GEM only at the moment since other sites require designs to be updated.

**Comment by tsepot** [comment]
@miltontony please note that the images do not seem to be updating on the front end, here are 2 articles I have added images on http://cms.tz.qa.gem.unicore.io/cms/post/20/ and http://cms.tz.qa.gem.unicore.io/cms/post/19/ I tried to upload different img dimensions, kindly assist. Please also clarify where the image shows after it has been uploaded.
