### ISSUE TITLE
When switching languages whilst on a post an error 404 is returned, the directory does not change.

### ISSUE THREAD

**Issue by tsepot** [universalcore/unicore#52]

**Comment by tsepot** [comment]
@miltontony please note that I am till returned an error 404.

**Comment by smn** [comment]
@tsepot can you include a link + screenshot of the page you're on when you're changing the language and the page that gives you the 404?

**Comment by miltontony** [comment]
@tsepot QA had not deployed properly, this should be working now. Please retest

**Comment by tsepot** [comment]
switch languages currently take you to the home page
