### ISSUE TITLE
MAMA, FFL: Internal Server Error after making changes on the CMS

### ISSUE THREAD

**Issue by tsepot** [universalcore/unicore#55]

**Comment by smn** [comment]
Do we have a sentry error or screenshot for this somewhere?

**Comment by miltontony** [comment]
@smn this is the same as the FFL save on sorting screen

**Comment by smn** [comment]
@miltontony are you closing this when we've separated the git pushing from the model saving?

**Comment by miltontony** [comment]
Yeah, I'll let that be the closing

**Comment by tsepot** [comment]
Please note that this does no longer occurs.
