### ISSUE TITLE
FFL: Make linking article functionality to show on front end

### ISSUE THREAD

**Issue by tsepot** [universalcore/unicore#58]

**Comment by smn** [comment]
@tsepot can you point me at a URL where you added a linked page up but didn't see it rendered on the front end?

**Comment by tsepot** [comment]
@smn recently added http://cms.tz.qa.ffl.unicore.io/cms/post/144/ http://tz.qa.ffl.unicore.io/content/detail/2bc3c4e418404dbe97c7baec7e6a04f9/

**Comment by smn** [comment]
but that doesn't link anywhere in the CMS yet https://github.com/universalcore/unicore-cms-content-ffl-tanzania/blob/master/gitpagemodel/2bc3c4e418404dbe97c7baec7e6a04f9/data.json#L11?

**Comment by smn** [comment]
![unicef___universal_core](https://cloud.githubusercontent.com/assets/1065/4580670/9dd4819e-4fd8-11e4-8a86-1ab24b45d94b.jpg)

This is what it looks like, still needs proper markup but at least it's showing.

**Comment by tsepot** [comment]
@smn and @miltontony Unable to test this might be cause by https://github.com/universalcore/unicore/issues/67 ?

**Comment by tsepot** [comment]
Please note that linking works fine on production
