### ISSUE TITLE
GEM: Make linking article functionality to show on front end

### ISSUE THREAD

**Issue by tsepot** [universalcore/unicore#59]

**Comment by smn** [comment]
@miltontony do we have any templates readily available for this?

**Comment by smn** [comment]
![girl_effect_mobile___universal_core](https://cloud.githubusercontent.com/assets/1065/4577943/cff845ba-4fc0-11e4-93a6-623196b38bc4.jpg)

**Comment by tsepot** [comment]
Article linking updates on qa http://tz.qa.gem.unicore.io/content/detail/bbbef1cb7d864fb78a69e5ee917b316a/
