### ISSUE TITLE
Content authors need to be able to administer tags (tags for you)

### ISSUE THREAD

**Issue by smn** [universalcore/unicore#6]
<a href="https://github.com/smn"><img src="https://avatars.githubusercontent.com/u/1065?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [smn](https://github.com/smn)**
_Friday Sep 12, 2014 at 14:18 GMT_
_Originally opened as https://github.com/universalcore/universalcore.github.io/issues/6_

---
### Is there clear value to clients/users (the grandma test)?

Tags are a secondary means of navigation (where the categories are primary).
Tags facilitate the discovery of loosely related content in a folksonomy.
Tags are to help both content authors & users to manage the content.
Multiple tags can be assigned to posts.
### Have real-world users been consulted in designing the feature?

Praekelt head of content.
### Can it be measured?

Binary.
### Can be shipped in 2-4 weeks?

Yes
### Has a mockup been created?

No.
### Did we pivot?

Known feature from previous projects.
### Is it coupled to a project?

MAMA needs it for tagging related content that spans multiple categories (like for example an "hiv" tag)
### Is it bloggable/slackable/tweetable?

Yes
### Compound value, will it be used elsewhere?

Yes, all content authored for UC will benefit from the ability to tag.
### Has a partner or client be consulted, interviewed?

No

**Comment by miltontony** [comment]
@smn you moved this to the `In QA` column. Was this done?

**Comment by smn** [comment]
Nope, accident, apologies.

**Comment by pippayeats** [comment]
For now: "Tags. These won't be displayed on the site. You can use them to gather information about how people are using your site." 

Later: "Tags for you. These won't be displayed on the site. You can use them to gather information about how people are using your site." and 
"Tags for your readers. These will be displayed on the site at the bottom of each article (etc). Use them to help people navigate around your site and find related articles."

**Comment by smn** [comment]
Adding a tag to a post:

![change_post___django_site_admin](https://cloud.githubusercontent.com/assets/1065/5202607/080e63b6-7588-11e4-9e6b-65aabf7fc73e.jpg)

Filtering posts on tags assigned:

![select_post_to_change___django_site_admin](https://cloud.githubusercontent.com/assets/1065/5202591/ed3a9500-7587-11e4-94bc-6a89424d211a.jpg)

List of tags known in the system:

![select_tag_to_change___django_site_admin](https://cloud.githubusercontent.com/assets/1065/5202612/1a048532-7588-11e4-84bb-a0a68c747e9a.jpg)

**Comment by miltontony** [comment]
@smn :guitar: rocking!

**Comment by smn** [comment]
Completed in https://github.com/universalcore/unicore-cms-django/pull/43

**Comment by smn** [comment]
In QA.
