### ISSUE TITLE
FFL content is not formatted properly

### ISSUE THREAD

**Issue by tsepot** [universalcore/unicore#60]

**Comment by smn** [comment]
It is being formatted properly, I suspect that the content in the CMS isn't being entered in correctly. Try putting in some other formatting like `**foo**` for bold text and see if that happens. I think Markdown needs an explicit empty line in order to separate paragraphs.

**Comment by smn** [comment]
![unicef___universal_core](https://cloud.githubusercontent.com/assets/1065/4580982/b2f1f4dc-4fdb-11e4-934f-17d49b2c12a9.jpg)

**Comment by miltontony** [comment]
@smn content was migrated from the Zambia site

**Comment by smn** [comment]
Ah makes sense!

**Comment by miltontony** [comment]
@smn @tsepot false alarm - it looks like the content wasn't imported properly - I did a bit more digging and it turns out the importing does work - the production version of FFL looks much better than QA, so I ran the import script again in QA and it looks great :)

**Comment by tsepot** [comment]
content format look fine
