### ISSUE TITLE
GEM: Please remove the date stamp (reported by Sarah) - Add image next to page for GEM

### ISSUE THREAD

**Issue by tsepot** [universalcore/unicore#61]

**Comment by pippayeats** [comment]
Can I get some background on the reason for removing a date stamp? Think this may be a specific use case and not sure it is relevant for the platform in general.

**Comment by miltontony** [comment]
@pippayeats I think this was discussed in the channel at length - there were arguments for both for and against. Tamsen argued that having a date stamp quickly dates content especially since our content isn't being updated frequently. @smn was against removing the timestamp. The compromise was to display the date stamp less prominently (possible at the bottom of the article)

**Comment by pippayeats** [comment]
@milton can we not have the option in the CMS to show or hide date stamp?

**Comment by miltontony** [comment]
Possibly. This ticket needs to be updated since things have changed since it was first created. We can probably discuss it further during sprint planning

**Comment by pippayeats** [comment]
Cool let's discuss during sprint planning

On 6 November 2014 10:29, Milton Madanda notifications@github.com wrote:

> Possibly. This ticket needs to be updated since things have changed since
> it was first created. We can probably discuss it further during sprint
> planning
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/universalcore/unicore/issues/61#issuecomment-61941841
> .

## 

_PHILLIPA YEATS_ | CREATIVE TECHNOLOGIST

_PRAEKELT_.COM | _PRAEKELTFOUNDATION_.ORG
M: +27720423133 |  Skype: pippayeats

**Comment by smn** [comment]
1. Remove from the homepage.
2. Remove from the article listings.
3. Publish the date subtly at the bottom of the article only.

**Comment by tsepot** [comment]
Date stamps removed on home page and article listing for GEM. They are included at the bottom of the article only.
