### ISSUE TITLE
Update MAMA to new designs

### ISSUE THREAD

**Issue by miltontony** [universalcore/unicore#75]

**Comment by SteveBarnett** [comment]
I'm going to ping Ruan and discuss.

**Comment by miltontony** [comment]
https://files.slack.com/files-pri/T024FKUV7-F02U0QS75/mama_mobisite_present.jpg
![image](https://cloud.githubusercontent.com/assets/623417/4940815/14b6c586-65de-11e4-90fc-8914c95011ab.png)

**Comment by KomaNelson** [comment]
The Baby Center logo is very small

![screen shot 2014-11-07 at 12 56 03 pm](https://cloud.githubusercontent.com/assets/377061/4951899/1062775c-666d-11e4-8baa-c6d4cb6fabdb.png)

**Comment by miltontony** [comment]
Please test this on a C1 and e250 - we changed the logo sizes to make sure they fit on the low-end devices. The larger images were looking really bad

**Comment by KomaNelson** [comment]
Still looks very small on the E250 and on the C1 as well.

Please see attached screenshots.

![photo 4](https://cloud.githubusercontent.com/assets/377061/4952917/10062328-667a-11e4-82f3-6ffcea83e5e0.JPG)
![photo 3 1](https://cloud.githubusercontent.com/assets/377061/4952916/10042e24-667a-11e4-8c2d-20af2ad0d8d1.JPG)
![photo 2 6](https://cloud.githubusercontent.com/assets/377061/4952914/10018f8e-667a-11e4-870c-cae8f7695630.JPG)
![photo 1 5](https://cloud.githubusercontent.com/assets/377061/4952915/1003b0b6-667a-11e4-908c-ee81dd47cef8.JPG)

**Comment by miltontony** [comment]
Yeah, if you look at the C1 - if the logo was any bigger, MAMA would get cut off. So we either need bigger logos (vertically) or need better designs for the logos. cc: tash
